---
kind: pipeline
type: docker
name: default

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: drone-test
